# Generated by Django 5.0.1 on 2025-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
